apiVersion: v1
kind: Pod
metadata:
  name: mysql-percona-debug-8.0-pod
  labels:
    app: debug-pod
    type: mysql-percona-debug-8.0
spec:
  containers:
  - name: debug-container
    image: percona:8.0.36-28@sha256:1128d56e64711ed65cb0c57041048967ee5875a2167d708d327885fd1f995fa0
    command: ['sleep', '3600']
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
        ephemeral-storage: "128Mi"
      limits:
        memory: "128Mi"
        ephemeral-storage: "128Mi"
  restartPolicy: Never

