apiVersion: v1
kind: Pod
metadata:
  name: network-debug-pod
  labels:
    app: debug-pod
    type: network-debug
spec:
  containers:
  - name: debug-container
    image: ghcr.io/c-gerke/k8s-debug-pods/network-debug:latest
    command: ['sleep', '3600']
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "32Mi"
        ephemeral-storage: "32Mi"
  restartPolicy: Never

