apiVersion: v1
kind: Pod
metadata:
  name: postgresql-percona-debug-13-pod
  labels:
    app: debug-pod
    type: postgresql-percona-debug-13
spec:
  containers:
  - name: debug-container
    image: percona/percona-postgresql-operator:2.5.0-ppg13-postgres
    command: ['sleep', '3600']
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
        ephemeral-storage: "128Mi"
      limits:
        memory: "128Mi"
        ephemeral-storage: "128Mi"
  restartPolicy: Never

